### ISSUE TITLE
Library doesn't have bitcode enabled

### ISSUE THREAD

**Issue by aeirola** [przelewy24/p24-mobile-lib-ios#1]
Hello,

Building a production release of our application using this library fails with the following error:

`ld: '.../ios/P24Lib/libP24.a(BankInfo.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7`

A workaround would be to disable bitcode for the application build, but this seems like a bad solution. Would you be able to provide a bitcode enabled build of the library?

**Comment by przelewy24** [comment]
Hi, we added bitcode version to repo, you can find it here: [https://github.com/przelewy24/p24-mobile-lib-ios/blob/master/libP24-bitcode.a](https://github.com/przelewy24/p24-mobile-lib-ios/blob/master/libP24-bitcode.a)

**Comment by aeirola** [comment]
Thanks for providing a bitcode enabled version as well.
