### ISSUE TITLE
XCFramework version doesn't seem to expose any modules

### ISSUE THREAD

**Issue by TheStalwart** [przelewy24/p24-mobile-lib-ios#10]
According to modulemap file, "import P24" should be possible, but Xcode 12.5 claims "No such module 'P24'".

The libP24.xcframework is added to Build Phases and Embedded Content sections in the same way as a different xcframework we use in the app.

**Comment by mareklat** [comment]
@TheStalwart Thanks for your bug report. The fix is already in the latest version of the SDK.
