### ISSUE TITLE
libPrzelewy24-lib-Secure.a does not contain bitcode

### ISSUE THREAD

**Issue by TheStalwart** [przelewy24/p24-mobile-lib-ios#11]
Our project has bitcode enabled because crash reporting was unreliable in "old" mode. Can you provide a version of library with bitcode enabled?

**Comment by TheStalwart** [comment]
Yesterday's build has the same issue

**Comment by mareklat** [comment]
@TheStalwart Check version 3.5.18. The library with bitcode is included as separate framework.
