### ISSUE TITLE
URI Scheme not working on ios with 3.5.41 version

### ISSUE THREAD

**Issue by wojtokuba** [przelewy24/p24-mobile-lib-ios#13]
When redirecting from ApplePay to mobile app URI scheme for example: app://payment/continue, an exception is occuring and uri scheme is not recognized as correct URI. 

The same redirect URI in safari is working fine. It might be a problem with WebKit browser. Unforetunately we're unable to debug it because of blocked debugger in library.

**Comment by wojtokuba** [comment]
A small update - it looks like when using in-browser "pay with card" function, apple pay is started and no p24ApplePayOnSuccess or error callbacks are called. This problem occurs only while using Apple Pay. When paying by online payment, events are fired.

**Comment by mareklat** [comment]
Can you provide more information about your case? What library method do you use? What parameters are passed in the registration process? Please describe to me step by step your payment flow.

**Comment by mareklat** [comment]
Closed due to no response
