### ISSUE TITLE
Missing translations of some messages in the library

### ISSUE THREAD

**Issue by michalkansy-re** [przelewy24/p24-mobile-lib-ios#14]
Hello. When I do payment on a foreign store e.g. Croatian, some messages generated by the library are still in Polish. Embedded P24 site is in the correct language (Croatian). Please see the below attached screenshots. This cause problems with App Store review, our apps are rejected due to a following reason: _Your app's alerts are written in Polish while the app is set to the Croatian localization. To help users understand what your app is saying, your app's alerts should be in the same language as your app's current localization._
![aa225298-73ed-4ece-93e3-bd8ca2214933](https://user-images.githubusercontent.com/86047020/212904032-cde4351c-0e6e-4b95-9200-7af68df5adbe.png)
![f5ac3994-09da-4e85-9dc0-63ab3d1cc013](https://user-images.githubusercontent.com/86047020/212904036-5d52642d-5d85-4a9b-ba07-44365bd983b3.png)
![b3c605be-7d36-49c9-8551-bc8c2c327633](https://user-images.githubusercontent.com/86047020/212904045-74498062-cc33-45ba-85f6-f96566acf1c5.png)

**Comment by mareklat** [comment]
We do not have official SDK support for this language. It is necessary to report a business need required by the merchant. Please contact our customer service department: support@przelewy24.pl. There you will get information on what to do to report a new functionality
