### ISSUE TITLE
New apps using latest Mobile SDK are no longer accepted by Apple because of UIWebView usage #15

### ISSUE THREAD

**Issue by piotr-marat** [przelewy24/p24-mobile-lib-ios#6]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by piotr-marat** [comment]
My bad - latest lib is actually fine. I'm closing it.

**Comment by dac14** [comment]
Hi, I'm using your latest SDK. I'm still receiving email from apple about usage of deprecated api usage (UIWebView). I've used grep to find files in my project that uses UIWebView and it shows me that  binary file ./.../libP24.a matches. Can you please verify that?

**Comment by piotr-marat** [comment]
> Hi, I'm using your latest SDK. I'm still receiving email from apple about usage of deprecated api usage (UIWebView). I've used grep to find files in my project that uses UIWebView and it shows me that binary file ./.../libP24.a matches. Can you please verify that?

I'm using latest lib24-bitcode.a - and Apple Store has accepted that one. I had this issue with some older one.

**Comment by mareklat** [comment]
I confirm that. UIWebView has been replaced by WKWebView in version 3.4.1. To be sure which version you're using, use the **P24.sdkVersion()** method.

**Comment by dac14** [comment]
I've checked sdk version, I'm using "3.5.1-ios". I'll try to verify other libraries probably one of the social logins are trolling me...

**Comment by piotr-marat** [comment]
> I've checked sdk version, I'm using "3.5.1-ios". I'll try to verify other libraries probably one of the social logins are trolling me...

I had this pain few weeks ago with react-native 0.59.* ecosystem. After upgrade to 0.62.2 problem disappeared.

**Comment by dac14** [comment]
In my case it was googleSignIn library imported to the project as binary. Thats why I wasn't able to find reference to UIWebView using `grep -r UIWebView .`. Case is closed 3.5.1 works fine with WKWebView :D
