### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by aerow69** [przelewy24/p24-mobile-lib-ios#7]
**New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).**

Using `grep -r "UIWebView" .` in my project give one result `Binary file ./P24/libP24-bitcode.a matches`.
When are you planning update?

**Comment by mareklat** [comment]
@aerow69 You need to upgrade library to newest version. See https://github.com/przelewy24/p24-mobile-lib-ios/issues/6

**Comment by aerow69** [comment]
Thanks. Clearing derived data and build folders help.
