### ISSUE TITLE
P24 missing architecture

### ISSUE THREAD

**Issue by twprzybysz** [przelewy24/p24-mobile-lib-ios#8]
I was trying to update the application which uses p24 framework but the compiler shows an error:

```
The linked library 'libP24-bitcode.a' is missing one or more architectures required by this target: armv7.
```

The newest version from the github:

```
lipo -info ibP24-bitcode.a
Architectures in the fat file: libP24-bitcode.a are: x86_64 arm64
```

The base library which I've been using:

```
lipo -info ibP24-bitcode.a
Architectures in the fat file: libP24-bitcode.a are: armv7 armv7s i386 x86_64 arm64 
```

Where's support for armv7?

**Comment by mareklat** [comment]
We decided to remove the support for this platform due to the low amount of devices supporting it. 
However, due to requests, we decided to come back to supporting these architectures for some time. Check version 3.5.6.
