### ISSUE TITLE
Redirect back to the app

### ISSUE THREAD

**Issue by n-popov-geniusee** [przelewy24/p24-mobile-lib-ios#9]
How can I make sdk to close WebView window after success transaction? 

We registering transaction via https://secure.przelewy24.pl/trnRegister and it require `p24_url_return` param. We are call `.startTrnRequestWithParams()` and pass token to it.  So, after success transaction webview page do redirect in that https page and sdk window is not closing

**Comment by mareklat** [comment]
@n-popov-geniusee Did you set the parameters `mobileLib=1` and `sdkVersion={version}` when registering the transaction?

**Comment by mareklat** [comment]
Closed due to no response
